//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTPlayground01.IntegrationTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DiffApiTestsExpectedResponses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiffApiTestsExpectedResponses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RESTPlayground01.IntegrationTests.DiffApiTestsExpectedResponses", typeof(DiffApiTestsExpectedResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;diffResultType&quot;:&quot;SizeDoNotMatch&quot;}.
        /// </summary>
        internal static string GetDiff_DifferentSize_200StatusAndResponseTextIsValid {
            get {
                return ResourceManager.GetString("GetDiff_DifferentSize_200StatusAndResponseTextIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;diffResultType&quot;:&quot;Equals&quot;}.
        /// </summary>
        internal static string GetDiff_EqualContent_200StatusAndResponseIsValid {
            get {
                return ResourceManager.GetString("GetDiff_EqualContent_200StatusAndResponseIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;diffs&quot;:[{&quot;offset&quot;:0,&quot;length&quot;:1},{&quot;offset&quot;:2,&quot;length&quot;:2}],&quot;diffResultType&quot;:&quot;ContentDoNotMatch&quot;}.
        /// </summary>
        internal static string GetDiff_SameSizeDifferentContent_200StatusAndResponseIsValid {
            get {
                return ResourceManager.GetString("GetDiff_SameSizeDifferentContent_200StatusAndResponseIsValid", resourceCulture);
            }
        }
    }
}
